name: cf-worker-deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    uses: mchangrh/actions/.github/workflows/cf-worker-2.yml@main
    secrets:
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }} 